### PR TITLE
feat: Update latest schemas to schema-store

### PR DESCRIPTION
**Pull request by mimotej**
Manual update to schema store from smaug, morty, infra and balrog clusters.
Part of https://github.com/open-services-group/scrum/issues/6

### CODE REVIEW

**Review by tumido — CHANGES_REQUESTED** [review]
please exclude `schemas` directory from pre-commit,

otherwise lgtm

**Comment by mimotej** [comment]
> please exclude `schemas` directory from pre-commit,
> 
> otherwise lgtm

Resolved

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
