### PR TITLE
feat: Add json schemas for CRDs

### PR DESCRIPTION
**Pull request by mimotej**
Adding JSON schemas for CRDs. 

How this was done:
Schemas were generated from OpenAPI endpoint of Smaug, Infra and Rick. After that these schemas were put together. 
While working on this I faced an issue described here https://cloud.redhat.com/blog/validating-openshift-manifests-in-a-gitops-world . Fortunately Andrew Block created a Python script that resolves the problems: https://github.com/sabre1041/k8s-manifest-validation/tree/main/scripts . Only had to add ` --strict ` to calling of `openapi2jsonschema` command inside script to acquire strict schemas. 
The schemas are store in `schemas/master-standalone-strict`. Where master is default version of schemas, standalone are de-referenced schemas (meaning not containing URL reference to specified github repository) and strict are schemas which do not allow arbitrary attributes.

Part of: https://github.com/operate-first/SRE/issues/107

### CODE REVIEW

**Review by tumido — CHANGES_REQUESTED** [review]
Can you please add a script/docs in a separate commit which would describe how were these schemas created? Without that nobody knows if they are correct, how to update it etc. 

Also, is there any need for the path to be `openshift-json-schema/master-standalone/`? Wouldn't just a `schemas` directory work just fine? Or `schemas/master` in case the `master` has any significance...

**Comment by larsks** [comment]
Re: @tumido's [earlier comment](https://github.com/operate-first/schema-store/pull/1#pullrequestreview-795299579), I would also like to see information on where these schemas are from and how they are generated included in this PR.

**Comment by mimotej** [comment]
Edited description of the PR so it explains the process that was done to acquire all schemas.

**Comment by larsks** [comment]
@mimotej I meant I wanted to see a README file at least so that someone visiting the repository in the future can understand where the data comes from and how to add new schemas.

**Comment by mimotej** [comment]
> @mimotej I meant I wanted to see a README file at least so that someone visiting the repository in the future can understand where the data comes from and how to add new schemas.

Forgot to mention sorry. I've already created small README in this PR: https://github.com/operate-first/schema-store/pull/2. I am planning on extending it tomorrow a little bit to explain how to add new schemas in more detail. Will try to do it tomorrow as soon as possible :+1: .

**Comment by larsks** [comment]
@tumido:

> Also, is there any need for the path to be openshift-json-schema/master-standalone/? Wouldn't just a schemas directory work just fine? Or schemas/master in case the master has any significance...

The directory name is required by `kubeval`.

**Review by larsks — APPROVED** [review]

**Review by HumairAK — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
